### ISSUE TITLE
[MTOOLCHAINS-39] Can't unzip/unjar maven-toolchain-1.0.jar that is available at Maven Central

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-toolchains-plugin#70]
**[Thomas Cunningham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tcunning)** opened **[MTOOLCHAINS-39](https://issues.apache.org/jira/browse/MTOOLCHAINS-39?redirect=false)** and commented

jar tvf maven-toolchain-1.0.jar that is available from maven central reports reasonable results https://repo.maven.apache.org/maven2/org/apache/maven/maven-toolchain/

However....

jar xvf doesn't work

❯ jar xvf maven-toolchain-1.0.jar
 inflated: META-INF
java.io.IOException: META-INF : could not create directory
    at jdk.jartool/sun.tools.jar.Main.extractFile(Main.java:1449)
    at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1364)
    at jdk.jartool/sun.tools.jar.Main.run(Main.java:409)
    at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)

unzip doesn't work

❯ unzip maven-toolchain-1.0.jar
Archive:  maven-toolchain-1.0.jar
replace META-INF? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: META-INF
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/MANIFEST.MF.
  inflating: org
checkdir error:  org exists but is not directory
                 unable to process org/apache.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/java.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/java/DefaultJavaToolchainFactory.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/java/JavaToolChain.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/java/DefaultJavaToolChain.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/ToolchainManagerPrivate.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/DefaultToolchain.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/ToolchainPrivate.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/MisconfiguredToolchainException.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/ToolchainManager.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/ToolchainFactory$1.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/model.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/model/ToolchainModel.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/model/PersistedToolchains.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/model/io.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/model/io/xpp3.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/model/io/xpp3/MavenToolchainsXpp3Reader.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/model/io/xpp3/MavenToolchainsXpp3Writer.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/RequirementMatcherFactory$ExactMatcher.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/Toolchain.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/RequirementMatcherFactory.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/RequirementMatcherFactory$1.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/ToolchainManagerPrivate$1.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/DefaultToolchainManager.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/ToolchainFactory.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/ToolchainManager$1.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/RequirementMatcherFactory$VersionMatcher.class.
checkdir error:  org exists but is not directory
                 unable to process org/apache/maven/toolchain/RequirementMatcher.class.
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/plexus.
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/plexus/components.xml.
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/maven.
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/maven/org.apache.maven.
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/maven/org.apache.maven/maven-toolchain.
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/maven/org.apache.maven/maven-toolchain/pom.xml.
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/maven/org.apache.maven/maven-toolchain/pom.properties.

 

---

**Affects:** 1.0

**Issue Links:**
- [MNG-7357](https://issues.apache.org/jira/browse/MNG-7357) All Maven Core JARs have unusual entry order

**Remote Links:**
- [Issue with Maven Central at Sonatype
](https://issues.sonatype.org/browse/MVNCENTRAL-7141)

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

no idea: please open a MVNCENTRAL issue https://issues.sonatype.org/projects/MVNCENTRAL
